# Generated by Django 4.1.5 on 2023-02-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Товар магазина', 'verbose_name_plural': 'Товары магазина'},
        ),
    ]
